//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.ServicioSUNAT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIResponse", Namespace="http://schemas.datacontract.org/2004/07/ServicesWCF.Class")]
    [System.SerializableAttribute()]
    public partial class APIResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string condDomiRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoCpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string condDomiRuc {
            get {
                return this.condDomiRucField;
            }
            set {
                if ((object.ReferenceEquals(this.condDomiRucField, value) != true)) {
                    this.condDomiRucField = value;
                    this.RaisePropertyChanged("condDomiRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errorCodeField, value) != true)) {
                    this.errorCodeField = value;
                    this.RaisePropertyChanged("errorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoCp {
            get {
                return this.estadoCpField;
            }
            set {
                if ((this.estadoCpField.Equals(value) != true)) {
                    this.estadoCpField = value;
                    this.RaisePropertyChanged("estadoCp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estadoRuc {
            get {
                return this.estadoRucField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoRucField, value) != true)) {
                    this.estadoRucField = value;
                    this.RaisePropertyChanged("estadoRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://microsoft.com/webservices/", ConfigurationName="ServicioSUNAT.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/ConsutarRUC", ReplyAction="http://microsoft.com/webservices/IService/ConsutarRUCResponse")]
        string ConsutarRUC(string numeroRUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/ConsutarRUC", ReplyAction="http://microsoft.com/webservices/IService/ConsutarRUCResponse")]
        System.Threading.Tasks.Task<string> ConsutarRUCAsync(string numeroRUC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/ConexionSunat", ReplyAction="http://microsoft.com/webservices/IService/ConexionSunatResponse")]
        WsComercialApp.ServicioSUNAT.APIResponse ConexionSunat(string urlToken, string urlConsulta, string clientId, string clientKey, string[] jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/ConexionSunat", ReplyAction="http://microsoft.com/webservices/IService/ConexionSunatResponse")]
        System.Threading.Tasks.Task<WsComercialApp.ServicioSUNAT.APIResponse> ConexionSunatAsync(string urlToken, string urlConsulta, string clientId, string clientKey, string[] jsonValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/EnviarMail", ReplyAction="http://microsoft.com/webservices/IService/EnviarMailResponse")]
        string EnviarMail(string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/EnviarMail", ReplyAction="http://microsoft.com/webservices/IService/EnviarMailResponse")]
        System.Threading.Tasks.Task<string> EnviarMailAsync(string XML);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/Base64Encode", ReplyAction="http://microsoft.com/webservices/IService/Base64EncodeResponse")]
        string Base64Encode(string plainText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/Base64Encode", ReplyAction="http://microsoft.com/webservices/IService/Base64EncodeResponse")]
        System.Threading.Tasks.Task<string> Base64EncodeAsync(string plainText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/Test", ReplyAction="http://microsoft.com/webservices/IService/TestResponse")]
        string Test(string Text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://microsoft.com/webservices/IService/Test", ReplyAction="http://microsoft.com/webservices/IService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync(string Text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WsComercialApp.ServicioSUNAT.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WsComercialApp.ServicioSUNAT.IService>, WsComercialApp.ServicioSUNAT.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConsutarRUC(string numeroRUC) {
            return base.Channel.ConsutarRUC(numeroRUC);
        }
        
        public System.Threading.Tasks.Task<string> ConsutarRUCAsync(string numeroRUC) {
            return base.Channel.ConsutarRUCAsync(numeroRUC);
        }
        
        public WsComercialApp.ServicioSUNAT.APIResponse ConexionSunat(string urlToken, string urlConsulta, string clientId, string clientKey, string[] jsonValue) {
            return base.Channel.ConexionSunat(urlToken, urlConsulta, clientId, clientKey, jsonValue);
        }
        
        public System.Threading.Tasks.Task<WsComercialApp.ServicioSUNAT.APIResponse> ConexionSunatAsync(string urlToken, string urlConsulta, string clientId, string clientKey, string[] jsonValue) {
            return base.Channel.ConexionSunatAsync(urlToken, urlConsulta, clientId, clientKey, jsonValue);
        }
        
        public string EnviarMail(string XML) {
            return base.Channel.EnviarMail(XML);
        }
        
        public System.Threading.Tasks.Task<string> EnviarMailAsync(string XML) {
            return base.Channel.EnviarMailAsync(XML);
        }
        
        public string Base64Encode(string plainText) {
            return base.Channel.Base64Encode(plainText);
        }
        
        public System.Threading.Tasks.Task<string> Base64EncodeAsync(string plainText) {
            return base.Channel.Base64EncodeAsync(plainText);
        }
        
        public string Test(string Text) {
            return base.Channel.Test(Text);
        }
        
        public System.Threading.Tasks.Task<string> TestAsync(string Text) {
            return base.Channel.TestAsync(Text);
        }
    }
}
