//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DocumentoDetalle
    {
        public string CompaniaSocio { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public int Linea { get; set; }
        public string TipoDetalle { get; set; }
        public string ItemCodigo { get; set; }
        public string Lote { get; set; }
        public string Condicion { get; set; }
        public string Descripcion { get; set; }
        public string UnidadCodigo { get; set; }
        public Nullable<decimal> CantidadPedida { get; set; }
        public Nullable<decimal> CantidadEntregada { get; set; }
        public string UnidadCodigoDoble { get; set; }
        public Nullable<decimal> CantidadPedidaDoble { get; set; }
        public Nullable<decimal> CantidadEntregadaDoble { get; set; }
        public Nullable<decimal> PrecioUnitarioOriginal { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> PrecioUnitarioFinal { get; set; }
        public Nullable<decimal> PrecioUnitarioDoble { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> MontoFinal { get; set; }
        public string IGVExoneradoFlag { get; set; }
        public string DespachoUnidadEquivalenteFlag { get; set; }
        public string ImprimirPUFlag { get; set; }
        public string AlmacenCodigo { get; set; }
        public string FlujodeCaja { get; set; }
        public string PrecioModificadoFlag { get; set; }
        public Nullable<decimal> AutorizacionNumero { get; set; }
        public string ExportacionMarcaPaquete { get; set; }
        public Nullable<decimal> ExportacionCantidadEmbarque { get; set; }
        public Nullable<System.DateTime> ExportacionFechaProgramacion { get; set; }
        public string ExportacionComentarios { get; set; }
        public string ExportacionSituacion { get; set; }
        public string ReferenciaFiscal02 { get; set; }
        public string NumeroSerie { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string TransferenciaGratuitaFlag { get; set; }
        public Nullable<decimal> PrecioUnitarioGratuito { get; set; }
        public Nullable<decimal> PorcentajeDescuento01 { get; set; }
        public Nullable<decimal> PorcentajeDescuento02 { get; set; }
        public Nullable<decimal> PorcentajeDescuento03 { get; set; }
        public string NoInventariado { get; set; }
        public string VentaPerdida { get; set; }
        public Nullable<decimal> StockCongelado { get; set; }
        public Nullable<decimal> NumeroPreventa { get; set; }
        public Nullable<decimal> AutorizacionNumeroQTY { get; set; }
        public Nullable<decimal> MontoComision { get; set; }
        public string OfertaNumero { get; set; }
        public string OfertaOrigen { get; set; }
        public Nullable<int> OfertaLinea { get; set; }
        public Nullable<decimal> OfertaPrecio { get; set; }
        public string ExportacionSituación { get; set; }
        public string Proyecto { get; set; }
        public string reprogramacionpuntollegada { get; set; }
        public string RutaDespacho { get; set; }
        public Nullable<System.DateTime> RutaDespachoFechaAsignacion { get; set; }
        public string RutaDespachoPlacaVehiculo { get; set; }
        public string UbigeoLlegada { get; set; }
        public string UbigeoPartida { get; set; }
        public string flg_detracciontransporte { get; set; }
        public string Formula { get; set; }
        public string ItemSerie { get; set; }
        public Nullable<decimal> LargoNumero { get; set; }
        public Nullable<decimal> MargenPorcentaje { get; set; }
        public string Material { get; set; }
        public string Modelo { get; set; }
        public string OrdenTrabajo { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public Nullable<decimal> PesoUnitario { get; set; }
        public Nullable<decimal> PorcentajeDescuento04 { get; set; }
        public Nullable<decimal> CantidadCancelada { get; set; }
        public Nullable<decimal> CantidadComprometida { get; set; }
        public string CentroCosto { get; set; }
        public Nullable<int> ClienteDireccionDespacho { get; set; }
        public string DireccionLlegada { get; set; }
        public string DireccionPartida { get; set; }
        public Nullable<int> DocumentoRelacLinea { get; set; }
        public string DocumentoRelacNumeroDocumento { get; set; }
        public string DocumentoRelacTipoDocumento { get; set; }
        public Nullable<decimal> Dureza { get; set; }
        public Nullable<int> Agro_Tienda { get; set; }
        public Nullable<decimal> AltoNumero { get; set; }
        public Nullable<decimal> AnchoNumero { get; set; }
        public Nullable<decimal> Auxiliar01Numero { get; set; }
        public Nullable<decimal> Auxiliar02Numero { get; set; }
        public Nullable<decimal> Auxiliar03Numero { get; set; }
        public string CadenaMedidas { get; set; }
        public Nullable<decimal> CantidadAutorizada { get; set; }
        public string afectoicbpflag { get; set; }
        public string AplicacionNumeroDocumento { get; set; }
        public string AplicacionTipoDocumento { get; set; }
        public Nullable<decimal> CantidadLote { get; set; }
        public Nullable<decimal> CantidadPedidaFinal { get; set; }
        public Nullable<decimal> CantidadSOD { get; set; }
        public string ClasificacionRotacion { get; set; }
        public Nullable<int> CodigoFlete { get; set; }
        public string CodigoSap { get; set; }
        public string comentario { get; set; }
        public string ComprometeFlag { get; set; }
        public Nullable<int> ContratoRelacSecuencia { get; set; }
        public Nullable<int> ControlBonificacion { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> CostoUnitarioPromedio { get; set; }
        public string DetraccionCodigo { get; set; }
        public Nullable<decimal> detraccionmontolocal { get; set; }
        public string DOT { get; set; }
        public string GuiaCompaniaSocio { get; set; }
        public string GuiaNumero { get; set; }
        public Nullable<int> GuiaSecuencia { get; set; }
        public string GuiaSerieNumero { get; set; }
        public string IndBonificacion { get; set; }
        public string ItemCodigoAux { get; set; }
        public string KitFlag { get; set; }
        public Nullable<int> LineaCorte { get; set; }
        public Nullable<int> lineaitemprincipal { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public Nullable<decimal> MargenPorcentajePromedio { get; set; }
        public Nullable<decimal> MargenPromedio { get; set; }
        public Nullable<decimal> MontoConvenio { get; set; }
        public Nullable<decimal> MontoDescuento { get; set; }
        public Nullable<decimal> MontoFlete { get; set; }
        public Nullable<int> NroCortes { get; set; }
        public Nullable<decimal> NroCortesFinal { get; set; }
        public string Ordendistribucion { get; set; }
        public Nullable<int> ordenitemprincipal { get; set; }
        public Nullable<decimal> PORCENTAJE01_VALIDA { get; set; }
        public Nullable<int> PrecioNumeroRegistro { get; set; }
        public Nullable<decimal> PrecioUnitarioConvenio { get; set; }
        public Nullable<decimal> PrecioUnitarioFlete { get; set; }
        public Nullable<decimal> PrecioUnitarioFlete02 { get; set; }
        public Nullable<decimal> PrecioUnitarioFleteOriginal { get; set; }
        public Nullable<int> PrefacturaSecuencia { get; set; }
        public Nullable<int> Promocion { get; set; }
        public Nullable<int> PromocionNumero { get; set; }
        public string ReferenciaFiscal01 { get; set; }
        public Nullable<int> ReferenciaLinea { get; set; }
        public string ReferenciaOrdenCompra { get; set; }
        public string SpaQuote { get; set; }
        public string TipoPromocion { get; set; }
        public string TransferenciaBonificacionFlag { get; set; }
        public string TransferenciaRepresentacionFla { get; set; }
        public string SpringCodigo { get; set; }
    
        public virtual CO_Documento CO_Documento { get; set; }
        public virtual CO_Documento CO_Documento1 { get; set; }
        public virtual CO_Documento CO_Documento2 { get; set; }
        public virtual CO_Documento CO_Documento3 { get; set; }
    }
}
