//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CO_Documento()
        {
            this.CO_DocumentoDetalle = new HashSet<CO_DocumentoDetalle>();
            this.CO_DocumentoDetalle1 = new HashSet<CO_DocumentoDetalle>();
            this.CO_DocumentoDetalle2 = new HashSet<CO_DocumentoDetalle>();
            this.CO_DocumentoDetalle3 = new HashSet<CO_DocumentoDetalle>();
            this.CO_DocumentoImpuesto = new HashSet<CO_DocumentoImpuesto>();
            this.CO_DocumentoImpuesto1 = new HashSet<CO_DocumentoImpuesto>();
            this.CO_DocumentoImpuesto2 = new HashSet<CO_DocumentoImpuesto>();
            this.CO_DocumentoImpuesto3 = new HashSet<CO_DocumentoImpuesto>();
            this.CO_DocumentoDetalleDespacho = new HashSet<CO_DocumentoDetalleDespacho>();
        }
    
        public string CompaniaSocio { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string EstablecimientoCodigo { get; set; }
        public string FormaFacturacion { get; set; }
        public Nullable<int> ClienteNumero { get; set; }
        public string ClienteRUC { get; set; }
        public string ClienteNombre { get; set; }
        public string ClienteDireccion { get; set; }
        public string ClienteReferencia { get; set; }
        public Nullable<int> ClienteCobrarA { get; set; }
        public Nullable<System.DateTime> FechaDocumento { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public string TipoFacturacion { get; set; }
        public string TipoVenta { get; set; }
        public string ConceptoFacturacion { get; set; }
        public string FormadePago { get; set; }
        public string Criteria { get; set; }
        public Nullable<int> Vendedor { get; set; }
        public Nullable<decimal> TipodeCambio { get; set; }
        public string MonedaDocumento { get; set; }
        public Nullable<decimal> MontoAfecto { get; set; }
        public Nullable<decimal> MontoNoAfecto { get; set; }
        public Nullable<decimal> MontoImpuestoVentas { get; set; }
        public Nullable<decimal> MontoImpuestos { get; set; }
        public Nullable<decimal> MontoDescuentos { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<decimal> MontoPagado { get; set; }
        public Nullable<decimal> MontoAdelantoSaldo { get; set; }
        public Nullable<int> PreparadoPor { get; set; }
        public Nullable<int> AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaPreparacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string NotaCreditoDocumento { get; set; }
        public string ComercialPedidoNumero { get; set; }
        public Nullable<System.DateTime> ComercialPedidoFechaRequerida { get; set; }
        public string AlmacenCodigo { get; set; }
        public string ImpresionPendienteFlag { get; set; }
        public string DocumentoMoraFlag { get; set; }
        public string ContabilizacionPendienteFlag { get; set; }
        public string VoucherPeriodo { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherAnulacion { get; set; }
        public string CentroCosto { get; set; }
        public string Proyecto { get; set; }
        public string CampoReferencia { get; set; }
        public string Sucursal { get; set; }
        public string TipoCanjeFactura { get; set; }
        public string LetraCarteraFlag { get; set; }
        public string LetraBanco { get; set; }
        public string LetraCobranzaNumero { get; set; }
        public string LetraAvalNombre { get; set; }
        public string LetraAvalRUC { get; set; }
        public string LetraAvalDireccion { get; set; }
        public string LetraAvalTelefono { get; set; }
        public string LetraAceptadoPor { get; set; }
        public string LetraUbicacion { get; set; }
        public Nullable<System.DateTime> LetraFechaRecepcion { get; set; }
        public string LetraDescuentoCuentaBancaria { get; set; }
        public Nullable<decimal> LetraDescuentoIntereses { get; set; }
        public string LetraDescuentoVoucherFlag { get; set; }
        public string LetraDescuentoVoucher { get; set; }
        public string LetraDescuentoCanjeFlag { get; set; }
        public string LetraDescuentoCanjeVoucher { get; set; }
        public string DescuentoFlag { get; set; }
        public string APTransferidoFlag { get; set; }
        public Nullable<int> APProcesoNumero { get; set; }
        public Nullable<int> APProcesoSecuencia { get; set; }
        public string CobranzaDudosaEstado { get; set; }
        public string CobranzaDudosaVoucher { get; set; }
        public string CobranzaDudosaVoucherClearing { get; set; }
        public Nullable<System.DateTime> CobranzaDudosaFecha { get; set; }
        public Nullable<System.DateTime> CobranzaDudosaFechaClearing { get; set; }
        public string UnidadNegocio { get; set; }
        public string UnidadReplicacion { get; set; }
        public string ProcesoImportacion { get; set; }
        public string ProcesoImportacionNumero { get; set; }
        public Nullable<System.DateTime> ProcesoImportacionFecha { get; set; }
        public string Comentarios { get; set; }
        public string ComentariosImprimirFlag { get; set; }
        public Nullable<decimal> ComentariosMonto { get; set; }
        public string NumeroInterno { get; set; }
        public string RutaDespacho { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public Nullable<decimal> MontoRedondeo { get; set; }
        public string LetraAceptadoFlag { get; set; }
        public string ClienteContacto { get; set; }
        public Nullable<int> ClienteDireccionSecuencia { get; set; }
        public string TransportistaChofer { get; set; }
        public string TransportistaVehiculo { get; set; }
        public string ReprogramacionMotivo { get; set; }
        public string ReprogramacionPuntoPartida { get; set; }
        public string ReprogramacionPuntoLlegada { get; set; }
        public Nullable<System.DateTime> APFechaTransferencia { get; set; }
        public string DocumentosinDespachoFlag { get; set; }
        public string DocumentosinCantidadFlag { get; set; }
        public Nullable<System.DateTime> RutaDespachoFechaAsignacion { get; set; }
        public string RutaDespachoPlacaVehiculo { get; set; }
        public Nullable<int> Cobrador { get; set; }
        public string LetraProtestoFlag { get; set; }
        public Nullable<int> AprobadoPorDescuento { get; set; }
        public Nullable<System.DateTime> FechaVencimientoOriginal { get; set; }
        public string NumeroContrato { get; set; }
        public string CentroCostoDestino { get; set; }
        public string CobranzaDudosaMotivo { get; set; }
        public Nullable<decimal> MontoImpuestoRetenido { get; set; }
        public Nullable<decimal> TransferenciaGratuitaIGVFactor { get; set; }
        public string LetraEstado { get; set; }
        public Nullable<decimal> LetraDescuentoPortes { get; set; }
        public Nullable<System.DateTime> LetraProtestoFecha { get; set; }
        public string LetraProtestoNDFlag { get; set; }
        public string LetraEstadoAnterior { get; set; }
        public string NumeroUnico { get; set; }
        public string WEB_UsuarioMobil { get; set; }
        public Nullable<decimal> WEB_Notaventa { get; set; }
        public string NotaVenta { get; set; }
        public string PlacaVehiculo { get; set; }
        public Nullable<int> DespachoDireccionSecuencia { get; set; }
        public Nullable<int> DespachoVehiculoflag { get; set; }
        public Nullable<decimal> MontoComision { get; set; }
        public Nullable<decimal> MontoComisionPagada { get; set; }
        public string Comentario01 { get; set; }
        public string Comentario02 { get; set; }
        public Nullable<int> ClasificacionCobranza { get; set; }
        public string Comentario03 { get; set; }
        public string DocumentoElectronicoFlag { get; set; }
        public string RecojoFlag { get; set; }
        public Nullable<int> ClienteDireccionDespacho { get; set; }
        public string CotizacionNumero { get; set; }
        public Nullable<System.DateTime> FechaOrdenCompra { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public string ComentarioAprobacion { get; set; }
        public string ObservacionFE { get; set; }
        public string PrecioModificadoFlag { get; set; }
        public string ProcesoFlag { get; set; }
        public Nullable<int> ProduccionSecuencia { get; set; }
        public string SIAF_Correlativo { get; set; }
        public string SIAF_Expediente { get; set; }
        public Nullable<System.DateTime> SIAF_FechaPago { get; set; }
        public string SIAF_Secuencia { get; set; }
        public string TransferProduccionFlag { get; set; }
        public Nullable<int> NumeroEnvio { get; set; }
        public string MontoRetenidoFlag { get; set; }
        public string NotaCreditoRelacionadas { get; set; }
        public Nullable<decimal> LetraPortes { get; set; }
        public string LetraPresentadaVoucher { get; set; }
        public Nullable<decimal> LetraProtesto { get; set; }
        public string LetraTipoNegociacion { get; set; }
        public string LicitacionNumeroProceso { get; set; }
        public string MEF_Estado { get; set; }
        public Nullable<decimal> MontoPercepcion { get; set; }
        public Nullable<decimal> MontoRetenido { get; set; }
        public Nullable<int> ImpresionNumero { get; set; }
        public string INT_EstadoEnvio { get; set; }
        public string INT_EstadoProceso { get; set; }
        public string INT_Secuencial { get; set; }
        public Nullable<decimal> LetraComisiones { get; set; }
        public Nullable<decimal> LetraIntereses { get; set; }
        public string LetraNumeroUnico { get; set; }
        public Nullable<int> LetraPersona { get; set; }
        public string LetraPlanillaBanco { get; set; }
        public Nullable<int> FEInternalNumber { get; set; }
        public string FENotaCreditoMotivo { get; set; }
        public string FENotaCreditoSustento { get; set; }
        public Nullable<int> FEResumenNumero { get; set; }
        public string flag_EstadoTransmision { get; set; }
        public Nullable<int> flag_resumendiario { get; set; }
        public Nullable<int> flg_resumendiario { get; set; }
        public string DiferidoDocumento { get; set; }
        public string DiferidoFlag { get; set; }
        public string EstadoEnviadoTCI { get; set; }
        public string EstadoSunat { get; set; }
        public string exportacionsituacion { get; set; }
        public Nullable<System.DateTime> FechaImpresion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> FEComunicadoNumero { get; set; }
        public string FEEstado { get; set; }
        public string FEHashCode { get; set; }
        public string DetraccionCodigo { get; set; }
        public Nullable<decimal> DetraccionMontoLocal { get; set; }
        public string DespachoFlag { get; set; }
        public string DecripcionEstadoSunat { get; set; }
        public Nullable<decimal> ComisionMonto { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> Cajero { get; set; }
        public string AlmacenConsignacion { get; set; }
        public string Cadena { get; set; }
        public string ActividadEconomica { get; set; }
        public string ArbitrioFlag { get; set; }
        public string CanalVenta { get; set; }
        public string CertificadoRetencion { get; set; }
        public Nullable<System.DateTime> CobranzaLegalFecha { get; set; }
        public string CobranzaLegalVoucher { get; set; }
        public string ComentarioAux1 { get; set; }
        public string ComentarioOrdenCompra { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> ContratoSecuencia { get; set; }
        public string Convenio { get; set; }
        public Nullable<decimal> CostoTotal { get; set; }
        public Nullable<decimal> CostoTotalPromedio { get; set; }
        public string DocumentoReferencia { get; set; }
        public string EnTransporte { get; set; }
        public string EquipoVenta { get; set; }
        public string ESWEBFLAG { get; set; }
        public Nullable<System.DateTime> FechaAnulacion { get; set; }
        public Nullable<System.DateTime> FechaCanje { get; set; }
        public Nullable<System.DateTime> FechaDocOriginal { get; set; }
        public Nullable<System.DateTime> FechaInicioTraslado { get; set; }
        public Nullable<System.DateTime> FechaRecepcionADV { get; set; }
        public Nullable<System.DateTime> FechaVencimientoDOT { get; set; }
        public Nullable<int> FEEnvioBaja { get; set; }
        public Nullable<int> FEENVIONUMERO { get; set; }
        public string flagnuevaversion { get; set; }
        public Nullable<int> Flg_ComunicadoBaja { get; set; }
        public Nullable<int> IdPrefactura { get; set; }
        public Nullable<int> IDTransportista { get; set; }
        public Nullable<decimal> LATITUD_ENTREGA { get; set; }
        public Nullable<decimal> LATITUDENTREGA { get; set; }
        public string LetraVoucherDiferido { get; set; }
        public Nullable<decimal> LONGITUD_ENTREGA { get; set; }
        public Nullable<decimal> LONGITUDENTREGA { get; set; }
        public Nullable<decimal> Margen { get; set; }
        public Nullable<decimal> MargenPorcentaje { get; set; }
        public Nullable<decimal> MargenPorcentajePromedio { get; set; }
        public Nullable<decimal> MargenPromedio { get; set; }
        public Nullable<decimal> MontoBruto { get; set; }
        public Nullable<decimal> MontoConvenio { get; set; }
        public Nullable<decimal> MontoDescuentosSISE { get; set; }
        public Nullable<decimal> MontoFlete { get; set; }
        public Nullable<decimal> MontoTotalLetra { get; set; }
        public string MotivoAnulacion { get; set; }
        public string MotivoNotaCredito { get; set; }
        public string NotaCreditoMotivo { get; set; }
        public string NotaCreditoSustento { get; set; }
        public string NotaIngreso { get; set; }
        public Nullable<int> NumeroCopias { get; set; }
        public Nullable<int> PedidoNumerado { get; set; }
        public string PercepcionDocumento { get; set; }
        public Nullable<decimal> PercepcionPorcentaje { get; set; }
        public Nullable<int> PromotorVenta { get; set; }
        public string REALIZADOPORWEB { get; set; }
        public string ReferenciaCompaniaOrden { get; set; }
        public string ReferenciaNumeroOrden { get; set; }
        public string ReferenciaTipoPago { get; set; }
        public string RequisicionNumero { get; set; }
        public string SERIEDOCUMENTO { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<decimal> TipodeCambioPactado { get; set; }
        public string TIPODOCUMENTOVENTA { get; set; }
        public string tipoformapagosunat { get; set; }
        public string TipoMotivo { get; set; }
        public string TransportistaBrevete { get; set; }
        public string TransportistaDireccion { get; set; }
        public string TransportistaMarca { get; set; }
        public string TransportistaNombre { get; set; }
        public string TransportistaPlaca { get; set; }
        public Nullable<int> TransportistaProvincia { get; set; }
        public string TransportistaRUC { get; set; }
        public Nullable<decimal> ValidezOferta { get; set; }
        public string Vendedor_all { get; set; }
        public string VentaSeparadoFlag { get; set; }
        public string SpringCodigo { get; set; }
        public string MotivoComunicado { get; set; }
        public string ObservacionEstadoFE { get; set; }
        public Nullable<System.DateTime> FechaRegistroResumen { get; set; }
        public string TramaFormaPago { get; set; }
        public Nullable<decimal> MontoPendientePago { get; set; }
        public string CodigoQR { get; set; }
        public string VentaEquipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoDetalle> CO_DocumentoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoDetalle> CO_DocumentoDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoDetalle> CO_DocumentoDetalle2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoDetalle> CO_DocumentoDetalle3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoImpuesto> CO_DocumentoImpuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoImpuesto> CO_DocumentoImpuesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoImpuesto> CO_DocumentoImpuesto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoImpuesto> CO_DocumentoImpuesto3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CO_DocumentoDetalleDespacho> CO_DocumentoDetalleDespacho { get; set; }
    }
}
