//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_DocumentoImpuesto
    {
        public string CompaniaSocio { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public string TipoRegistro { get; set; }
        public string Impuesto { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        public virtual CO_Documento CO_Documento { get; set; }
        public virtual CO_Documento CO_Documento1 { get; set; }
        public virtual CO_Documento CO_Documento2 { get; set; }
        public virtual CO_Documento CO_Documento3 { get; set; }
    }
}
