//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_LetraCompromiso
    {
        public string NumeroSolicitud { get; set; }
        public Nullable<decimal> ClienteNumero { get; set; }
        public Nullable<int> ClienteDireccionSecuencia { get; set; }
        public Nullable<decimal> Vendedor { get; set; }
        public Nullable<int> LetrasCantidad { get; set; }
        public Nullable<int> LetrasIntervalo { get; set; }
        public Nullable<System.DateTime> LetrasFechaBase { get; set; }
        public string Comentarios { get; set; }
        public string Estado { get; set; }
        public string PreparadorPor { get; set; }
        public Nullable<System.DateTime> PreparadoFecha { get; set; }
        public string GeneradoPor { get; set; }
        public Nullable<System.DateTime> GeneradoFecha { get; set; }
        public Nullable<System.DateTime> UltimafechaModif { get; set; }
        public string DiasAddFlag { get; set; }
        public Nullable<System.DateTime> TransferenciaFecha { get; set; }
        public Nullable<decimal> TransferenciaCanje { get; set; }
    }
}
