//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO_OperacionCanjeDetalle
    {
        public string CompaniaSocio { get; set; }
        public int OperacionCanjeNumero { get; set; }
        public int Linea { get; set; }
        public string TipoDocumento { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string InputOutputFlag { get; set; }
        public Nullable<decimal> MontoComision { get; set; }
    
        public virtual CO_OperacionCanje CO_OperacionCanje { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje1 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje2 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje3 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje4 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje5 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje6 { get; set; }
        public virtual CO_OperacionCanje CO_OperacionCanje7 { get; set; }
    }
}
