//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrelativosMast
    {
        public string CompaniaCodigo { get; set; }
        public string TipoComprobante { get; set; }
        public string Serie { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> CorrelativoNumero { get; set; }
        public Nullable<int> CorrelativoDesde { get; set; }
        public Nullable<int> CorrelativoHasta { get; set; }
        public string AlmacenCodigo { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public string DatawindowObjeto { get; set; }
        public string FeEnvio { get; set; }
        public string FeFlag { get; set; }
        public string Impresora { get; set; }
        public string ImpresoraFlag { get; set; }
        public string TipoLogo { get; set; }
        public string FETipoComprobanteRef { get; set; }
        public string UltimoUsuarioAct { get; set; }
        public Nullable<System.DateTime> UltimaFechaAct { get; set; }
    }
}
