//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_ClienteVendedor
    {
        public int Cliente { get; set; }
        public int Secuencia { get; set; }
        public Nullable<int> Vendedor { get; set; }
        public Nullable<System.DateTime> FechaDesde { get; set; }
        public Nullable<System.DateTime> FechaHasta { get; set; }
        public string Estado { get; set; }
        public string TipoVenta { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string UltimoUsuario { get; set; }
        public string Linea { get; set; }
    }
}
