//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class SY_Preferences
    {
        public string Usuario { get; set; }
        public string Preference { get; set; }
        public string AplicacionCodigo { get; set; }
        public string TipoValor { get; set; }
        public string ValorString { get; set; }
        public Nullable<int> ValorNumero { get; set; }
        public Nullable<System.DateTime> ValorFecha { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
    }
}
