//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.Models.Bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Usuario1 { get; set; }
        public string UsuarioPerfil { get; set; }
        public string Nombre { get; set; }
        public string Clave { get; set; }
        public string ExpirarPasswordFlag { get; set; }
        public Nullable<System.DateTime> FechaExpiracion { get; set; }
        public Nullable<System.DateTime> UltimoLogin { get; set; }
        public Nullable<int> NumeroLoginsDisponible { get; set; }
        public Nullable<int> NumeroLoginsUsados { get; set; }
        public string SQLLogin { get; set; }
        public string SQLPassword { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string UsuarioRed { get; set; }
        public string ClaveWeb { get; set; }
        public string ClaveSecundaria { get; set; }
        public string ApiKey1 { get; set; }
        public string CorreoElectronico { get; set; }
        public string HoraFin { get; set; }
        public string HoraFinAp { get; set; }
        public string HoraInicio { get; set; }
        public string HoraInicioAp { get; set; }
        public Nullable<int> PersonaNumero { get; set; }
    }
}
