//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsComercialApp.fonts
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_FormadePago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_FormadePago()
        {
            this.MA_FormadePagoDetalle = new HashSet<MA_FormadePagoDetalle>();
            this.MA_FormadePagoDetalle1 = new HashSet<MA_FormadePagoDetalle>();
            this.MA_FormadePagoDetalle2 = new HashSet<MA_FormadePagoDetalle>();
            this.MA_FormadePagoDetalle3 = new HashSet<MA_FormadePagoDetalle>();
        }
    
        public string FormadePago { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionExtranjera { get; set; }
        public string CreditoFlag { get; set; }
        public string ImportacionFlag { get; set; }
        public string Estado { get; set; }
        public string UltimoUsuario { get; set; }
        public Nullable<System.DateTime> UltimaFechaModif { get; set; }
        public string ClasificacionPago { get; set; }
        public string AutorizacionFlag { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string CuotaCreditoFlag { get; set; }
        public Nullable<int> NumeroCuotas { get; set; }
        public string CREDITOFLAGFE { get; set; }
        public string CompaniaCodigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_FormadePagoDetalle> MA_FormadePagoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_FormadePagoDetalle> MA_FormadePagoDetalle1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_FormadePagoDetalle> MA_FormadePagoDetalle2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_FormadePagoDetalle> MA_FormadePagoDetalle3 { get; set; }
    }
}
